name: CI

on: 
  push:

jobs:
  build:
    runs-on: macos-latest
    name: Ruby ${{ matrix.version }}
    strategy:
      matrix:
        version: [2.5, 2.6, 2.7]

    steps:
      - uses: actions/checkout@v2
      # - name: Cache node modules
      # uses: actions/cache@v2
      # env:
      #   cache-name: cache-node-modules
      # with:
      #   # npm cache files are stored in `~/.npm` on Linux/macOS
      #   path: ~/.npm
      #   key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-build-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Set up Ruby ${{ matrix.version }}
        uses: actions/setup-ruby@v1
        with: 
          ruby-version: ${{ matrix.version }}
      - name: Set up Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install Dependencies
        run: |
          bundle install --path vendor/cache
          yarn
      - name: Run Tests
        run: |
          yarn test
          bundle exec rake test
          
